### ISSUE TITLE
Sect 4.1 : what is the recommendation for middleboxes/NATs?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#183]
Sect 4.1 : This contains a statement on the recommendations for middleboxes and NATs, that I can’t understand, and this concerns me.
i.e. to me, the present text suggests that the advice in BCP 127 (aka RFC4787) should be changed for QUIC. I don’t recall this being discussed - was it?

I don’t actually follow the rationale that says this follows from QUIC being connection-oriented. If the connection close was visible to the device, and it could release state - then this might make sense, but that isn’t exactly what is explained. I’m left unsure how a “QUIC-aware” middlebox is supposed to track this state.

I'm also unsure how say a NAPT could know the traffic was QUIC, is this suggesting a port-based change. I think I need to understand this proposal.

**Comment by mirjak** [comment]
Actually we don't change the recommendation of RFC4748 as it says

"A NAT UDP mapping timer MUST NOT expire in less than two minutes"

However, we cite this wrongly, which is now addressed in PR #208.

The reason for recommending longer time-outs for QUIC is because you can be sure that there is handshake and the other end did confirm its willingness to communicate. Of course having a stopping indication would be better but we don't have it.

We don't recommend a specific value, nor do we say one should use equally long timers as for TCP. However, given you know there is valid communication on-going between the two peers a longer timer (of at least a couple if minutes) would probably be useful in a lot of cases.

Do we need more text here? @gorryfair do you want to propose something? Or should I?

Otherwise we can also discuss this at the next meeting!
