### ISSUE TITLE
App: Section 12 on Versioning 

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#199]
- I don’t have comments on the validity of the discussion text in section 12 and  the described procedures, but I do wonder why this is information for an application designer, rather than for managing operations. Is this the correct ID for this information? and if its is, could it be explained a little more to what the app designer needs too know.
- This section seems rather devoid of useful references. please add some.

**Comment by mirjak** [comment]
The split here was see as applicability is addressed at people who want to use QUIC (application designer but also people deploying QUIC at servers) and manageability for people who have to handle QUIC traffic (mainly network operator incl probably data centre operators). I know the split between the two last categories (deploying servers and managing a dc networks) is not always that clear. It's probably this section and the one about load balancing in manageability. I'm open to discuss where which section belongs. Do we need to bring this to the meeting?

@gorryfair what kind of reference are you think of?

**Comment by gorryfair** [comment]
* On what to do in Manageability: I'd suggest we write some text that says: 
"QUIC provides a version negotiation process, that allows new versions to be introduced. The deployment of new versions is discussed in section 12 of [ID. ietf-quic-applicability]."
Maybe even just as the first para of Manageability: Sect: 2.8.
* I meant add reference to section 6 in QUIC Transport - to both these documents

**Comment by mirjak** [comment]
There is already section 2.8 on "Version Negotiation and Greasing" and section 3.1.1. on "Identifying Negotiated Version" in the manageability draft. Ideally the idea is to not have cross reference between manageability and applicability.

I added a reference to section 6 of the quic-transport draft in manageability (see PR #260). Not sure we need that reference also in the applicability draft because that section actually doesn't require any knowledge of the internals on how version negotiation works...
