### ISSUE TITLE
App: Ref: Sect 1: Cite RFC8055 here?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#202]
I think RFC8055 generally applies to apps implemented over datagram, and QUIC is different to TCP  and so there are numerous details that are controlled by the application - so I’m thinking that even though QUIC operates as a transport, RFC8055 still has important advice to how to use QUIC, should this be cited in section 1?

**Comment by gorryfair** [comment]
Is RFC8085 normative (rather than info) to any application built on UDP?

**Comment by mirjak** [comment]
Not sure. RFC8085 applies to the design of QUIC for sure. However, for applications that use QUIC, I don't think much of RFC8085 applies. We have one reference in the keep-alive section. Where appropriate we can add more reference (you would need to tell me where) but otherwise I think most of the advise in RFC8085 is either replaced with explicit advise in this document or not required to consider for an application using QUIC.

**Comment by gorryfair** [comment]
That might have been so when QUIC was targeting HTTP, but now the datagram work exposes more, I'm less sure that this really is the case.

**Comment by mirjak** [comment]
QUIC datagrams is only not reliable but still uses congestion control. I can double-check but I still think most of RFC8085 does not apply. Or do you already have something specific in mind?

**Comment by gorryfair** [comment]
I just wanted to be sure, we can close this issue.
