### ISSUE TITLE
Network management of Path MTU

### ISSUE THREAD

**Issue by chris-box** [quicwg/ops-drafts#210]
The manageability draft aims to provide guidance to network operators in managing QUIC traffic, yet currently says nothing about what could be a major impact for some networks.

Consider a cellular/mobile network that is providing internet access to end users. Because it is an internet access service, the users have an implicit expectation that the complete range of internet packet sizes (i.e. up to 1500 bytes) can be exchanged. And as it is a cellular network packets are routinely encapsulated in GTP-U. The network operator also chooses to add IPSEC encapsulation in order to secure communications over a diverse range of connectivity providers. Since at least some of that connectivity is over paths with 1500 MTU, it implies that end-user datagrams over a certain size (e.g. 1400) would have to be fragmented at the point of encapsulation, and reassembled before delivery to the user.

Such fragmentation and reassembly comes at a cost. Importantly it implies a limited capacity for packets with sizes in the relevant range (e.g. 1400-1500). In a world where TCP dominates this is easily managed with MSS Clamping, so that both TCP endpoints learn the optimal size to use. In QUIC a different mechanism is required. QUIC-TRANSPORT describes how the endpoints can discover a hard path MTU limit, i.e. one where there is a clear cutoff above a certain size. I think the manageability draft needs a section that advises operators of networks where there is a soft path MTU limit. I'll create a PR with proposed wording for this section.

If anyone is unconvinced about the need for such packet size limitation, happy to discuss in more depth.

**Comment by ianswett** [comment]
I agree that what you're describing is a real problem, but given QUIC packets have the DF bit set, shouldn't that indicate to these networks that the QUIC packets should not be fragmented?

We have seen networks similar to what you're describing that appear to ignore the DF bit, which I believe goes against the assumptions in https://tools.ietf.org/html/rfc8899

**Comment by chris-box** [comment]
I'll give two answers to this. First is the technical reason. In a cellular network this pattern can arise:
![Fragmentation](https://user-images.githubusercontent.com/56736263/107362466-b2c61580-6ad0-11eb-8e2f-751d012a9a0d.jpg)
Because the IPSEC gateway acts on a packet that is already encapsulated, it naturally looks at the lower-layer IP header rather than the user's original IP header that had the DF bit set. Furthermore even if it performed deeper inspection and was able to take note of the DF, it would not have the ability to generate ICMP towards the server.

The second is the customer expectation reason. Clearly we could configure a router upstream of the PGW to have a lower MTU interface towards the PGW. This would force the router to drop the largest packets if they had DF set. And if they didn't set it, they would be fragmented (for v4). For mainstream internet services this would be ok, and few would notice. But with a large customer base, it is extremely likely that somebody will have a service that fails to work over such a network. At the end of the day people are paying for a "normal" internet service, and at least some of them will expect 1500 byte packets to be deliverable. Would you be happy for your home internet to be one that could never support packets larger than 1400 bytes?

**Comment by gorryfair** [comment]
Thanks for this explanation.

If a GTP tunnel encapsulates an IP packet that has DF set, and it does not set DF in the encapsulating packet, that tunnel needs to provide the necessary mechanisms to reassemble packets that are fragmented along the tunnelled path - that adds complexity at the lower layer, but it's allowed - providing that it does not clear DF.

Some paths support an MTU larger than 1500 B, many home access networks support an MTU smaller than 1500 B. That's why we have PMTU discovery methods. I note GTP is not alone in wishing take-on support for a larger PMTU. Many layer 2's also transparently fragment, but this isn't something that the IETF should advocate per protocol (even though TCP-MSS clamping works in cases for instance when IPsec isn't used).   

I don't see any specific need for anything in QUIC, or in guidance for QUIC. This is an IP-layer decision. A tunnel/encaps needs to support the MTU that it offers. Documenting the ways in which this can happen has been a long saga in the IETF: https://tools.ietf.org/html/draft-ietf-intarea-tunnels-10.

**Comment by chris-box** [comment]
Gorry, thanks for the feedback. The tunnels draft is not that easy to follow when it gets into dense discussion. However I do like the recognition that in ICMP there's no way to say "bigger than I'd like, but I can deal with if needed". That is essentially the problem here. We have a network that can handle large packets up to a certain percentage of the traffic (because it provides the necessary mechanisms), but it can't do that for the entire web.

So if I'm understanding you correctly, a network that does not want to carry all port 443 at 1500 bytes should handle this by using PMTU discovery methods to guide senders appropriately. That is essentially what I'm proposing in the PR.

Why is this particularly, uniquely, relevant to QUIC? Because HTTP is the bulk of internet traffic today, and clients and servers have incentives to adopt HTTP/3. This will radically alter the present ratio of TCP:UDP, and all such networks with reassembly capacity limits will benefit from a warning that their existing TCP MSS clamping will no longer protect them.

**Comment by ianswett** [comment]
From an attempt to deploy Path MTU from server to client, we saw a large number of paths where a larger MTU worked when probing, but sometime after increasing the MTU, the connection was black-holed.  The solution was to switch back to the original handshake MTU after a certain period of black-holing, which avoided the connection failing.

However, when this was more widely enabled, we saw:
 1) Complaints from operators who couldn't handle the excess traffic at higher MTUs
 2) User visible issues(app-level timeouts) on some ISPs

This was the most user-visible issue I can recall our deployment having in the last few years, and it was completely unexpected, at least for me, because I was unaware of this 'can handle large packets up to a certain percentage of the traffic' form of network operations.  Additionally, it was quite difficult to link the second issue to PathMTU discovery.

I can imagine a number of operator changes which would make our past PathMTU algorithm safe.  One is to never fragment UDP 443 when DF is set(or it's IPv6).

I'm not sure when we'd expect to see such changes deployed.  In the meantime, I can think of a few options I don't particularly like:
1) Don't try probing up past some fixed size(1400 bytes of payload?) which could cause fragmentation.
2) Don't try PathMTU for certain ASNs.
3) Adopt much more complex probing strategies that are optimized to quickly detect when a user is on one of these networks.

Chris, do you think it's reasonable to expect this can be changed in existing networks in 2021 or is this a multi-year process?

**Comment by chris-box** [comment]
There seem to be two questions to answer here.

Q1: Which guidance should we give to network operators in this draft?

I think it is pretty clear - if your network has one of these soft limits, you should drop oversized UDP/443 and send ICMP PTB. You will need to do this at a point in the network where you can easily send the PTB. This may be upstream of the point where fragmentation would have occurred. You raise the question of whether this should also occur if it's (IPv4 and DF is not set). I think we can leave that choice to implementations. Personally I would say do it regardless. If it's QUIC, and DF is not set, then packets are not supposed to be larger than 1200 anyway.

I would say it's reasonable to expect that this can be changed in 2021.

Q2: Which advice should we give to endpoints to help them avoid issues over networks that haven't implemented the guidance yet?

Perhaps before exceeding 1400 bytes of (IP header + UDP header + QUIC) the client could also do a conventional TCP handshake and take note of the MSS? If it has been clamped this information could be stored and used to inform packet size decisions.

Unfortunately the server doesn't have this option so it comes down to your three options, or a fourth which is to only migrate to HTTP/3 over a period of weeks. During that migration look for per-ASN degradation in metrics compared to HTTP/2. I would hope that networks that are then encountering capacity limits would be sufficiently on the ball to do something about it. If they complain to you, point them to the relevant section of the manageability draft.

**Comment by ianswett** [comment]
> There seem to be two questions to answer here.
> 
> Q1: Which guidance should we give to network operators in this draft?
> 
> I think it is pretty clear - if your network has one of these soft limits, you should drop oversized UDP/443 and send ICMP PTB. You will need to do this at a point in the network where you can easily send the PTB. This may be upstream of the point where fragmentation would have occurred. You raise the question of whether this should also occur if it's (IPv4 and DF is not set). I think we can leave that choice to implementations. Personally I would say do it regardless. If it's QUIC, and DF is not set, then packets are not supposed to be larger than 1200 anyway.
> 
> I would say it's reasonable to expect that this can be changed in 2021.
>

Thanks, that's good news, since it means there's no need to make any changes to the core QUIC documents.  However, in order for them to change their configs, they have to be made aware of this new recommendation.  Is this something that should be publicized on NOG lists once we have consensus on text for the manageability draft?  Or is there a better way to ensure the right people are notified?
 
> Q2: Which advice should we give to endpoints to help them avoid issues over networks that haven't implemented the guidance yet?
> 
> Perhaps before exceeding 1400 bytes of (IP header + UDP header + QUIC) the client could also do a conventional TCP handshake and take note of the MSS? If it has been clamped this information could be stored and used to inform packet size decisions.
> 
> Unfortunately the server doesn't have this option so it comes down to your three options, or a fourth which is to only migrate to HTTP/3 over a period of weeks. During that migration look for per-ASN degradation in metrics compared to HTTP/2. I would hope that networks that are then encountering capacity limits would be sufficiently on the ball to do something about it. If they complain to you, point them to the relevant section of the manageability draft.

I agree that having a relevant section would help.

**Comment by chris-box** [comment]
> Is this something that should be publicized on NOG lists once we have consensus on text for the manageability draft? Or is there a better way to ensure the right people are notified?

There are a number of forums where it could be publicised, national and international. BT are plugged into many of them so I can do my bit.

**Comment by martinthomson** [comment]
So a few things here:

QUIC isn't going to run on port 443 exclusively.  Traffic might be identifiable as QUIC, but the wire image is pretty hard to distinguish.  However, I think it's OK to recommend PTB rather than fragmentation for IP packets that might be QUIC.  (Other UDP protocols need to deal with those anyway.)

I don't think that information about the TCP MTU is transferrable to UDP, even if several other parts of the 5-tuple are the same.

Overall, I think it would be terrible if people had to have per-ASN state just to deploy the protocol.  Google might be able to deploy that, but we couldn't afford it.

**Comment by chris-box** [comment]
Yes, accurate distinguishability of QUIC is hard, and yes you could find it on any UDP port. But imagine a case where the network operator is blissfully unaware, until critical alarms pop up warning that a particular element of the network is overloaded, and there is end-to-end measured packet loss. Reactively finding the bulk flows that are driving this is not hard, because they will be obvious.

So any proactive management to avoid this occurring will rely on predictions of where QUIC will be found. The obvious one is HTTP/3, to be found in roughly the same port number distribution as  HTTP/2 (not h2c), i.e. ~99% is 443. Others can be added to this set if they are expected to become sufficiently prominent.

Coming to the other points:
If the received TCP MSS is not useful as a predictor for UDP MTU, then I guess that's ruled out.

I don't think per-ASN state is a _requirement_ for deployment. But as in any significant change, the early adopters will find the issues first. Even when being first, the speed of rollout you select will influence the size of those issues. The good news is that a gradual rollout across a range of clients and servers will collectively drive fixes across networks to support QUIC well.

**Comment by gorryfair** [comment]
I haven't looked whether TCP-MSS is a useful and usable hint when searching for a UDP MTU, it might be, or not - In many cases the TCP MSS *is* clamped; and it can be lower than the PMTU (even using TCP probe segments), so that might be an indicator... but I also see this does not help longer term.

I do agree that we need to avoid a network operator being "blissfully unaware, until critical alarms pop up"... and this seems the correct document to call something out - and maybe the best thing might indeed be to suggest that reassembled PMTUs are *only* used for apps profiles that really need it (until such apps are -eventually- updated) or where the network processing cost is understood and does not introduce an unwanted bottleneck/blackhole. Otherwise the path ought to drop and send an ICMP PTB message - and we can note that newer mechanisms are robust to loss of this PTB.

**Comment by martinthomson** [comment]
I agree with Gorry.  Only deploy fragmentation and reassembly where you **know** it will help.  Any uncertainty and the best advice is don't.  Even without DF.  Ignoring DF when the type of traffic is not known seems more like malice than anything else.

**Comment by chris-box** [comment]
I'd be happy with wording in the PR that articulated a general principle that if you have fragmentation and reassembly in your network, you should look to avoid passing DF traffic through this unless you really have to. The necessary drop of DF packets should occur at a point in the network where it is possible to generate the PTB, which may be distant from the point of fragmentation.

That's the general principle and end goal. In 2021, many network operators are likely to make only more targetted changes towards that goal, for the reasons I gave to Mirja in #212.
