### ISSUE TITLE
Is manageability about version 1

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#232]
There's a lot of text that acknowledges the differences between version 1 and any version, but it's not really consistent throughout.

For instance, [Section 2.2](https://quicwg.org/ops-drafts/draft-ietf-quic-manageability.html#section-2.2) describes coalescing, which is specific to version 1, without making this distinction.

I think that it would be better if it were explicitly about version 1, with those places where properties invariant called out.

**Comment by mirjak** [comment]
Section 2 already says 

```
This document describes version 1 of the QUIC protocol, whose wire image is fully defined in [QUIC-TRANSPORT] and [QUIC-TLS].
```

**Comment by martinthomson** [comment]
Indeed it does, but it isn't very good at sticking to that.  Probably worth just addressing at those points that the text goes off on a tangent.

**Comment by mirjak** [comment]
Actually we got this feedback about versions a couple of times. And we tried to make it clear when it got pointed out. But maybe there are still places where it is not clear. So if you have more cases where it should explicitly pointed out, please tell us where. Otherwise we can try to have full read focus on this aspect later on when all other issues are resolved.
