### ISSUE TITLE
Endpoint cooperation for DoS mitigation

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#240]
[Section 4.4](https://quicwg.org/ops-drafts/draft-ietf-quic-manageability.html#section-4.4) talks at length about detecting and mitigating against (D)DoS attacks, but this is written with the assumption of an uncooperative endpoint (likely to be, but unstated, a server).  All except the Retry text where the design specifically forces interventions to be cooperative.

It is entirely reasonable for DoS classification to be done with full knowledge of valid connection IDs or at least valid connection ID lengths.  If you allow for cooperation, the text might then explain how this might allow established flows to be separated from spoofed flows and new connection attempts.

**Comment by gorryfair** [comment]
+1 Perhaps either approach could be reasonable depending on the specific case? - Which DoS/DDoS mitigation fits best for an enterprise/user might vary depending on many things - including the role played by the endpoint and who controls the network and devices.

**Comment by mirjak** [comment]
Can someone propose text?

**Comment by ianswett** [comment]
In the last paragraph, it may be worth mentioning the 3x amplification limit during the handshake as well.

Post-handshake DoS/DDoS is usually an application-level property which could affect TCP as much as QUIC, so the whole 5-tuple/CID aspect seems like it could be ignored commonly post-handshake.

Is there a DoS expert we could ask to look at this text to see if it made sense, since I worry none of us are that person?

**Comment by ximaera** [comment]
@ianswett with TCP, the handshake could be completed by the DDoS "classification" engine without passing a bit of an information to the endpoint. That was, uh, a cool feature since otherwise the endpoint would've been flooded by handshake attempts. Even though TCP wasn't cooperating, this feature was powerful enough to allow to build an impenetrable DDoS mitigation infrastructure.

**Comment by gorryfair** [comment]
I was thinking of something a little like this (and can make a PR if this is heading in a useful direction:

"On-path observation of the transport headers of packets can be used for various security functions. For example, Denial of Service (DOS) and Distributed DOS (DDOS) attacks against the infrastructure or against an endpoint can be detected and mitigated by characterising anomalous traffic. Other uses include support for security audits (e.g., verifying the compliance with ciphersuites); client and application fingerprinting for inventory; and to provide alerts for network intrusion detection and other next generation firewall functions. When using an encrypted transport, it is possible for endpoints to directly support these security functions; another method could use an on-path network device that relies on pattern inferences in the traffic and heuristics or machine learning instead of processing observed header information." 
Thoughts?

**Comment by mirjak** [comment]
I think this text still doesn't address MT's original point fully - that an endpoint could even cooperate with an on-path device directly by e.g. sharing information about connection IDs.

**Comment by gorryfair** [comment]
Yes. Would happily add that the endpoint can "cooperate with an on-path device directly by e.g. sharing information about connection IDs". Is there more?

**Comment by britram** [comment]
Re: @ximaera comment above: SYN proxying won't work in QUIC for the obvious crypto reasons, but a related approach that dynamically starts sending Retry over a certain rate limit might be almost as good. Retries are already partially covered in section 4.7. In this regime one could also drop 0RTT packets. Is this something it'd make sense to add to this document, or in QUIC-LB instead?
