### ISSUE TITLE
draft-ietf-quic-manageability-10 Feedback 4.5

### ISSUE THREAD

**Issue by jaredmauch** [quicwg/ops-drafts#290]
You should really cite the port avoidance prior art: avoid-v4-udp-ports.  bind9 implemented this in #1440 which was implemented to avoid the problems that occurred after UDP/1434 was filtered by providers in response to the SQL Slammer attacks and the long term filtering that was left in place after this.

Is there a described technique or measurement to determine what ports may be problematic?  

Many operators have had to mitigate the damage of UDP based protocols on their networks and in attempt to limit the impact to well behaving ports and protocols deployed things in a limited scope, eg:

https://mailman.nanog.org/pipermail/nanog/2018-March/094350.html
http://mailman.nlnog.net/pipermail/nlnog/2018-March/002697.html

Large and small network operators are known to block or restrict ports and protocols due to the impact.   Akamai also has this implemented at our network edge in some locations today.

We have seen other protocols, eg: NTP start to move from 123 <-> 123 communication eg: draft-ietf-ntp-port-randomization which will face similar issues.  

Is there a way to provide feedback of what ports may be limited or should be avoided?  How would an operator signal or configure this?

**Comment by mirjak** [comment]
Currently most QUIC implementations are HTTP/3 and therefore use the https port 443. However QUIC is a general purpose transport protocol and therefore future application will likely use different ports. Also ports are not really meaningful to identify applications and as such I don't think there is any good advise we could give here. Or what are you missing? Can you maybe propose text?

Please also not that PR #305 proposes a (mostly) editorial update of this section.

**Comment by mirjak** [comment]
@jaredmauch can we close this issue?

**Comment by britram** [comment]
I think this is a very interesting question, but it's a bit outside the scope of this document (as a user's manual for the wire image)...

**Comment by jaredmauch** [comment]
> @jaredmauch can we close this issue?

At your own peril I guess.  The question here of how this protocol will work long distance on networks that have had to deal with abusive applications is still a going concern.  I'll review the changes that went in via #305 but ignoring how other UDP based applications have had to avoid ports but doing it at a protocol level will result in poor performance for some flows.

network operators deployed these only after the pain from the protocol and application users reached a tipping point where it was no longer feasible to operate a network without these protections.  It's unclear to me how this transport will work reliably as more ports are likely to be added to operator policers over time.

**Comment by LPardue** [comment]
I agree with Brian and Mirja. This is an interesting question but since there is no single port number for the QUIC transport, I find that the question verges into an applicability / deployment concern. We don't really have a document that covers that aspect of things today and I don't think we have enough experience with QUIC deployments to write an answer to the question yet. If the market figures out that, for example, any port other that UDP 443 is slow, then that seems an ok outcome while we figure things out. 

There is no transport-level mechanism defined by QUIC for service discovery. QUIC requires Application Protocol Layer Negotiation (ALPN) be used when opening a connection, so listening applications can share the same port number and dynamically dispatch QUIC flows based on the selected application. The reduces some of the concerns about QUIC-based applications competing for UDP numbers.
