### ISSUE TITLE
Dropping of UDP traffic

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#296]
Comment from @martinthomson from PR #272 on UDP Policing about this phrase:

`space that corresponds to the fraction of UDP traffic one wishes to drop.`

"The extra words don't really help here. If anything, you need to highlight the need to block only a subset of addresses rather than a subset of packets."

**Comment by chris-box** [comment]
I'd like to question whether arbitrarily applying a limit to UDP flows is a sensible recommendation over the coming years. QUIC will dominate internet traffic (I will estimate 85% or more, by bandwidth, mainly due to HTTP/3). In that end state what is the protective value of setting a ceiling on the amount of UDP? Yes it permits continuation of service for some during an unmitigated UDP DDoS, if they can switch to TCP. But in the presence of active mitigation, perhaps a limit is unwise?

**Comment by mirjak** [comment]
This document is not at all recommending to set such a limit. It's just saying that if you really think you need that limit, here is the way to do it right. However, maybe we should be more clear that this is not a recommendation for such a limit.

**Comment by mirjak** [comment]
Proposed some wording uptakes in #305
