### ISSUE TITLE
Are we recommending shorter timeouts for middleboxes?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#346]
> [RFC4787] requires a timeout that is not less than 2 minutes for most UDP traffic. However, in practice, timers are sometimes lower, in the range of 30 to 60 seconds.

As this is advice for network operators and middlebox vendors, this reads to me as permission to use a lower timeout.  I think that it still makes sense to maintain the recommendation in RFC 4787.  The advice for applications (don't rely on 2 minutes) still applies, but a 2 minute recommendation is worth sticking to.

**Comment by mirjak** [comment]
I thought the text is pretty clear in saying that a bit later:

```
For these reasons, the limits in {{?RFC4787}} are important to avoid black-holing of packets (and hence avoid interrupting the flow of data to the client), especially where devices are able to distinguish QUIC traffic from other UDP payloads.
```

I would rather want to keep this part because the message really is: yes we know these too short timers are implemented for UDP but please, please use at least 2 minutes for QUIC.

Maybe removing some paragraph breaks would make it clearer that these parts belong together?

Also this part got now edited quite extensively, so I rather not change it again...

**Comment by gorryfair** [comment]
Each of the sentences looks fine to me, but together I also have a hard time seeing the recommendation v. current experience. Here is a proposal: #350.
