### ISSUE TITLE
Point out how troubleshooting gets easier

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#63]
The section on "Passive network performance measurement and troubleshooting" is probably a bit too pessimistic.

It's probably worth pointing out that one part of network troubleshooting -- "find out which box to blame" -- is substantially easier. Thanks to integrity protection, most middleboxes, can drop, delay/rate limit, and corrupt, and that's about it. These are fairly easy behaviors to diagnose.

I've had some conversations with customers afraid of not having their TCP headers anymore, and I believe this fear is largely misguided.

If people agree this belongs in the draft, I can file a PR.

**Comment by mirjak** [comment]
I agree the wording is very pessimistic. However, I don't think your observation belongs in this section because it's about measurement of performance metrics.

There is a sentence in the introduction:

"Given QUIC is an end-to-end transport protocol, all information in the protocol header, even that which can be inspected, is is not meant to be mutable by the network, and is therefore integrity-protected to the extent possible."

Maybe it makes sense to add another sentence right there to also emphasis the positive effect of that, like: 

"While more limited information compared to TCP is visible to the network, integrity protection can also make troubleshooting easier as none of the nodes on the network path can modify the transport layer information."

**Comment by britram** [comment]
closed by #64
