### ISSUE TITLE
Double check use of normative language

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#85]
Not clear if these documents should use normative language at all. The applicability statement also sometimes uses normative language to recommend the implementation of certain interfaces; I don't think this is the right document for that but as we also don't have another document, we should decide if we want to do that or not!

**Comment by britram** [comment]
Manageability is a user's guide to the wire image, as such there's no sense to normative language (though I suppose some might like to add MUST NOT observe packets).

Since applicability is in part a set of recommendations to application designers, normative language might make sense there... but the document is informational, so normative language here has to reference or be trivially derived from normative language in one of the base drafts.

To simplify things, I'd just scrub all the SHOULDs, MAYs, and MUSTs.
